### ISSUE TITLE
Serving originals instead of 736x makes some images inavalid

### ISSUE THREAD

**Issue by khurshid-alam** [attilaolah/pinfeed#2]
According to this commit f60729be59d3eeb0e4c9d5ddefab3619f79dec21, it has started using `originals` instead of `736x` in the thumbnail url. While this works for most images, it makes some images invalid.

For example:

This pin:
https://www.pinterest.com/pin/360991726359457088/

The default image url is 
https://s-media-cache-ak0.pinimg.com/736x/ca/97/05/ca97055d647b2f5531f1b5f7ac7d2b67.jpg

But if I replace `736x` with `originals`, it will show following error:

https://s-media-cache-ak0.pinimg.com/originals/ca/97/05/ca97055d647b2f5531f1b5f7ac7d2b67.jpg

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>originals/ca/97/05/ca97055d647b2f5531f1b5f7ac7d2b67.jpg</Key>
<RequestId>DC5A1FCAA3770EAE</RequestId>
<HostId>j+ug65LorlbtBfJiaflW3XA6s0FkZ8EzLY18bzBYD5DLUerEO/Uy0uI6G6FEfE8X</HostId>
</Error>
```

I am not sure why `originals` is not available for that image. But may be there is a way to figure out which one has large image size and which one is limited to `736x`.

**Comment by khurshid-alam** [comment]
@attilaolah 

Update: I think using `1200x` could be the solution here. It is same as using `originals` for most images, and it doesn't make a image invalid (yet).

?

**Comment by attilaolah** [comment]
Well, let's see.
